/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function addClickOutsideListener(jsFn: (...args: any[]) => any): number
export declare function removeClickOutsideListener(id?: number | undefined | null): void
