
export const DEFAULT_SERVICE_SETTINGS = {
  isEnabled: true,
  isHibernationEnabled: false,
  isWakeUpEnabled: true,
  isNotificationEnabled: true,
  isBadgeEnabled: true,
  isMediaBadgeEnabled: false,
  trapLinkClicks: false,
  useFavicon: false,
  isMuted: false,
  customIcon: false,
  isDarkModeEnabled: false,
  isProgressbarEnabled: false,
  // Note: Do NOT change these default values. If they change, then the corresponding changes in the recipes needs to be done
  hasDirectMessages: true,
  hasIndirectMessages: false,
  hasNotificationSound: false,
  hasTeamId: false,
  hasCustomUrl: false,
  hasHostedOption: false,
  allowFavoritesDelineationInUnreadCount: false,
  disablewebsecurity: false,
  spellcheckerLanguage: false,
  onlyShowFavoritesInUnreadCount: false,
  isProxyFeatureEnabled: false,
  proxyHost: '',
  proxyPort: 0,
  proxyUser: '',
  proxyPassword: '',
  darkReaderBrightness: 100,
  darkReaderContrast: 90,
  darkReaderSepia: 10,
};
