/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function addClickOutsideListen(jsFn: (...args: any[]) => any): number
export declare function removeClickOutsideListen(id?: number | undefined | null): void
